import type { Metadata } from "next";
import "./globals.css";
import TailwindIndicator from "./components/TailwindIndicator";
import Header from "./components/Header";
import { ThemeProvider } from "./components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className="min-h-screen relative text-gray-700 bg-white dark:text-gray-100 dark:bg-ctm-navy-800 font-kosugi-maru">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="container mx-auto px-4 py-4">{children}</main>
        </ThemeProvider>
        <TailwindIndicator />
      </body>
    </html>
  );
}
