import type { Metadata } from "next";
import { Kosugi_Maru } from "next/font/google";
import "./globals.css";
import TailwindIndicator from "./TailwindIndicator";
import Header from './components/Header';

const kosugi_maru = Kosugi_Maru({
  variable: "--font-kosugi-maru",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="jp" style={kosugi_maru.style}>
      <body>
        <Header />
        {children}
        <TailwindIndicator />
      </body>
    </html>
  );
}