import type { Metadata } from "next";
import "./globals.css";
//import { Noto_Sans_JP } from "next/font/google";
import { Kosugi_Maru } from "next/font/google";

//const noto_sans_jp = Noto_Sans_JP({
//  variable: "--font-noto-sans-jp",
//  subsets: ["latin"],
//  weight: ["400", "700"],
//});
const kosugiMaru = Kosugi_Maru({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={kosugiMaru.className}>
      <body>{children}</body>
    </html>
  );
}
